### PR TITLE
Feature/connection with jti

### PR DESCRIPTION
**Pull request by lagartoverde**
Would like to have this merged because I'm having problems with having the 2 stacks running concurrently in order to test JTI

### CODE REVIEW

**Comment by nvdk** [comment]
why do we need cors here?

**Comment by lagartoverde** [comment]
Because it needs to be requested from GN and was giving a cors error there

**Comment by nvdk** [comment]
to expand, cors headers are typically handled in the identifier

**Comment by elpoelma** [comment]
Frontend GN seems to correctly fetch from the preview endpoint of this service when creating a new regulatory statement. The dropdown with the different published templates correctly shows up.

**Review by elpoelma — APPROVED** [review]

**Pull request merged**
